Repository Team-Port/Voilio-Backend, pull requests merged in 2023-04, with the labels that each got.

#29 (#27)feat/update comment
  src/main/java/com/techeer/port/voilio/domain/comment/controller/CommentController.java
  src/main/java/com/techeer/port/voilio/domain/comment/dto/request/CommentInfo.java
  src/main/java/com/techeer/port/voilio/domain/comment/dto/request/CommentUpdateRequest.java
  src/main/java/com/techeer/port/voilio/domain/comment/entity/Comment.java
  src/main/java/com/techeer/port/voilio/domain/comment/exception/NotFoundCommentException.java
  src/main/java/com/techeer/port/voilio/domain/comment/service/CommentService.java
  src/main/java/com/techeer/port/voilio/global/common/BaseEntity.java
  src/main/java/com/techeer/port/voilio/global/error/ErrorCode.java
  src/main/java/com/techeer/port/voilio/global/result/ResultCode.java
  src/main/java/com/techeer/port/voilio/global/result/ResultResponse.java
Labels: 기능 구현

#32 (#17)feat/update board
  src/main/java/com/techeer/port/voilio/domain/board/controller/BoardController.java
  src/main/java/com/techeer/port/voilio/domain/board/entity/Board.java
  src/main/java/com/techeer/port/voilio/domain/board/repository/BoardRepository.java
  src/main/java/com/techeer/port/voilio/domain/board/service/BoardService.java
  src/main/java/com/techeer/port/voilio/global/result/ResultCode.java
Labels: 기능 구현

#34 (#33)feat/delete comment
  src/main/java/com/techeer/port/voilio/domain/comment/controller/CommentController.java
  src/main/java/com/techeer/port/voilio/domain/comment/entity/Comment.java
  src/main/java/com/techeer/port/voilio/domain/comment/service/CommentService.java
  src/main/java/com/techeer/port/voilio/global/result/ResultCode.java
Labels: 기능 구현

#30 (#28)feat/create user
  build.gradle
  src/main/java/com/techeer/port/voilio/domain/user/controller/UserController.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/request/UserRequest.java
  src/main/java/com/techeer/port/voilio/domain/user/entity/User.java
  src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
  src/main/java/com/techeer/port/voilio/global/config/SecurityConfig.java
Labels: 기능 구현, 환경 세팅

#46 (#45)!hotfix
  src/main/java/com/techeer/port/voilio/domain/board/controller/BoardController.java
  src/main/resources/application.yml
Labels: 오류 수정

#52 [#51]Chore: !HOTFIX issue label 추가
  .github/ISSUE_TEMPLATE/!HOTFIX.md
Labels: 환경 세팅

#43 (#31)feat/get user list
  src/main/java/com/techeer/port/voilio/domain/user/controller/UserController.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/request/UserRequest.java
  src/main/java/com/techeer/port/voilio/domain/user/entity/User.java
  src/main/java/com/techeer/port/voilio/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
  src/main/java/com/techeer/port/voilio/global/result/ResultCode.java
Labels: 기능 구현

#53 (#44)feat/find board by category
  src/main/java/com/techeer/port/voilio/domain/board/controller/BoardController.java
  src/main/java/com/techeer/port/voilio/domain/board/repository/BoardRepository.java
  src/main/java/com/techeer/port/voilio/domain/board/service/BoardService.java
  src/main/java/com/techeer/port/voilio/global/common/Category.java
Labels: 기능 구현

#57 (#54)feat/find board by user
  src/main/java/com/techeer/port/voilio/domain/board/controller/BoardController.java
  src/main/java/com/techeer/port/voilio/domain/board/repository/BoardRepository.java
  src/main/java/com/techeer/port/voilio/domain/board/service/BoardService.java
  src/main/java/com/techeer/port/voilio/domain/user/repository/UserRepository.java
Labels: 기능 구현

#59 (#58)refactor/board refactor
  src/main/java/com/techeer/port/voilio/domain/board/controller/BoardController.java
  src/main/java/com/techeer/port/voilio/domain/board/mapper/BoardMapper.java
  src/main/java/com/techeer/port/voilio/domain/board/repository/BoardRepository.java
  src/main/java/com/techeer/port/voilio/domain/board/service/BoardService.java
Labels: 리팩토링
