Repository Team-Port/Voilio-Backend, pull requests merged in 2023-10, with the labels that each got.

#87 (#86) 새로 가입한 5명의 유저 조회하는 API, 팔로우상태인지 확인하는 API 구현
  src/main/java/com/techeer/port/voilio/domain/chat/dto/request/CreateChatRoomRequest.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/controller/SubscribeController.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/dto/request/CheckSubscribeRequestDto.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/dto/request/SubscribeRequest.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/repository/SubscribeRepository.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/service/SubscribeService.java
  src/main/java/com/techeer/port/voilio/domain/user/controller/UserController.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/response/Top5LatestMemberResponseDto.java
  src/main/java/com/techeer/port/voilio/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
Labels: 오류 수정, 기능 구현

#96 (#93)refactor/userrepository
  src/main/java/com/techeer/port/voilio/domain/board/service/BoardService.java
  src/main/java/com/techeer/port/voilio/domain/comment/entity/Comment.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/service/SubscribeService.java
  src/main/java/com/techeer/port/voilio/domain/user/controller/AuthController.java
  src/main/java/com/techeer/port/voilio/domain/user/controller/UserController.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/request/UserSignUpRequest.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/response/UserResponse.java
  src/main/java/com/techeer/port/voilio/domain/user/entity/User.java
  src/main/java/com/techeer/port/voilio/domain/user/mapper/UserMapper.java
  src/main/java/com/techeer/port/voilio/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/port/voilio/domain/user/service/AuthService.java
  src/main/java/com/techeer/port/voilio/domain/user/service/CustomUserDetailService.java
  src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
Labels: 리팩토링

#98 Hotfix: 93번 브랜치 머지 후 컴파일에에러 이슈
  src/main/java/com/techeer/port/voilio/domain/chat/controller/ChatRoomController.java
  src/main/java/com/techeer/port/voilio/domain/chat/service/ChatRoomService.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/repository/SubscribeRepository.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/service/SubscribeService.java
  src/main/java/com/techeer/port/voilio/domain/user/controller/UserController.java
  src/main/java/com/techeer/port/voilio/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
Labels: !HOTFIX

#100 Fix: Dto의 빌더패턴 삭제에 따른 로직 수정
  src/main/java/com/techeer/port/voilio/domain/user/controller/AuthController.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/request/UserSignUpRequest.java
  src/main/java/com/techeer/port/voilio/domain/user/entity/User.java
  src/main/java/com/techeer/port/voilio/domain/user/mapper/UserMapper.java
  src/main/java/com/techeer/port/voilio/domain/user/service/AuthService.java
Labels: 오류 수정, 리팩토링

#104 (#101)fix/auth
  src/main/java/com/techeer/port/voilio/domain/board/exception/NoAuthority.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/controller/SubscribeController.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/dto/SubscribeDto.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/mapper/SubscribeMapper.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/repository/SubscribeRepository.java
  src/main/java/com/techeer/port/voilio/domain/user/controller/AuthController.java
  src/main/java/com/techeer/port/voilio/domain/user/controller/UserController.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/UserDto.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/request/UserLoginRequest.java
  src/main/java/com/techeer/port/voilio/domain/user/entity/User.java
  src/main/java/com/techeer/port/voilio/domain/user/service/AuthService.java
  src/main/java/com/techeer/port/voilio/domain/user/service/CustomUserDetailService.java
  src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
  src/main/java/com/techeer/port/voilio/global/config/JpaAuditingConfig.java
  src/main/java/com/techeer/port/voilio/global/config/WebConfig.java
  src/main/java/com/techeer/port/voilio/global/config/security/JwtAccessDeniedHandler.java
  src/main/java/com/techeer/port/voilio/global/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/techeer/port/voilio/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/techeer/port/voilio/global/config/security/JwtProvider.java
  src/main/java/com/techeer/port/voilio/global/config/security/JwtSecurityConfig.java
  src/main/java/com/techeer/port/voilio/global/config/security/SecurityUtil.java
  src/main/java/com/techeer/port/voilio/global/config/security/TokenDto.java
  src/main/java/com/techeer/port/voilio/global/config/security/WebConfig.java
  src/main/java/com/techeer/port/voilio/global/config/security/WebSecurityConfig.java
  src/main/java/com/techeer/port/voilio/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: 오류 수정, 기능 구현, 리팩토링

#106 (#105)feat/comments
  src/main/java/com/techeer/port/voilio/VoilioApplication.java
  src/main/java/com/techeer/port/voilio/domain/comment/controller/CommentController.java
  src/main/java/com/techeer/port/voilio/domain/comment/dto/CommentDto.java
  src/main/java/com/techeer/port/voilio/domain/comment/dto/request/CommentInfo.java
  src/main/java/com/techeer/port/voilio/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/techeer/port/voilio/domain/comment/dto/request/CommentUpdateRequest.java
  src/main/java/com/techeer/port/voilio/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/techeer/port/voilio/domain/comment/entity/Comment.java
  src/main/java/com/techeer/port/voilio/domain/comment/mapper/CommentMapper.java
  src/main/java/com/techeer/port/voilio/domain/comment/repository/CommentRepository.java
  src/main/java/com/techeer/port/voilio/domain/comment/service/CommentService.java
  src/main/java/com/techeer/port/voilio/domain/user/controller/AuthController.java
  src/main/java/com/techeer/port/voilio/domain/user/controller/UserController.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/UserSimpleDto.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/response/Top5LatestMemberResponseDto.java
  src/main/java/com/techeer/port/voilio/domain/user/dto/response/Top5LatestUserResponseDto.java
  src/main/java/com/techeer/port/voilio/domain/user/mapper/UserMapper.java
  src/main/java/com/techeer/port/voilio/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/port/voilio/domain/user/service/AuthService.java
  src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
  src/main/java/com/techeer/port/voilio/global/common/BaseEntity.java
  src/main/java/com/techeer/port/voilio/global/config/OpenApiConfig.java
  src/main/java/com/techeer/port/voilio/global/result/ResultCode.java
Labels: 오류 수정, 기능 구현, 리팩토링

#108 (#107)fix/upload video board
  src/main/java/com/techeer/port/voilio/domain/board/controller/BoardController.java
  src/main/java/com/techeer/port/voilio/domain/board/mapper/BoardMapper.java
  src/main/java/com/techeer/port/voilio/domain/board/mapper/BoardMapperInterface.java
  src/main/java/com/techeer/port/voilio/domain/board/repository/BoardRepository.java
  src/main/java/com/techeer/port/voilio/domain/board/service/BoardService.java
  src/main/java/com/techeer/port/voilio/global/config/EmbeddedRedisConfig.java
  src/test/java/com/techeer/port/voilio/domain/board/repository/BoardRepositoryTest.java
Labels: 오류 수정, 리팩토링, !HOTFIX

#115 (#113)refactor/following user board list
  src/main/java/com/techeer/port/voilio/domain/subscribe/controller/SubscribeController.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/dto/SubscribeSimpleDto.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/exception/AlreadySubscribe.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/exception/AlreadyUnsubscribe.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/mapper/SubscribeMapper.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/repository/SubscribeRepository.java
  src/main/java/com/techeer/port/voilio/domain/subscribe/service/SubscribeService.java
  src/main/java/com/techeer/port/voilio/global/error/ErrorCode.java
  src/main/java/com/techeer/port/voilio/global/result/ResultCode.java
Labels: 기능 구현, 리팩토링
